In [1]:
import selenium

In [2]:
import webdriver_manager

In [3]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd

In [4]:
options=webdriver.ChromeOptions()

In [5]:
driver=webdriver.Chrome(options=options)

In [6]:
driver.get('https://www.myntra.com/')

In [7]:
search=driver.find_element(By.XPATH,".//input[@class='desktop-searchBar']")

In [8]:
search.send_keys("smart watches")

In [9]:
search.send_keys(Keys.ENTER)

In [10]:
product=driver.find_elements(By.XPATH,".//h4[@class='product-product']")
products=[i.text for i in product]

In [11]:
print(products)

['Cobra AMOLED Smart Watch', 'Women 1.27" Smart Watch', 'Rock AMOLED Display Smartwatch', 'Unisex Wave Genesis Smartwatch', 'Fit Posh Smartwatch', 'Supernova Bluetooth SmartWatch', 'Watch Pro', 'Ace XR 1.43" Smart Watches', 'Hive 1.39" Display Smart Watch', 'Women 1.27" Smart Watch', 'Mettle EliteEdition Smartwatch', 'Hulk 1.78 inch Smartwatch', 'Celia 1.32" Display SmartWatch', 'Eclipse Luxe 1.43" Amoled', 'Cosmos Ultra 1.91" BT Calling Smartwatch', 'Starlight Bluetooth Smartwatch', 'Ultima Connect Max HD Display', 'ColorFit Vision 3 Smartwatch', 'Fit Posh Smartwatch', 'Hurricane Smartwatch', 'Ultima BT Calling Smartwatch', 'Aura BT Calling Smartwatch', 'ColorFit Icon 2 Smartwatch', 'Hulk 1.78 inch Smartwatch', 'Watch Pro', 'Cosmos Ultra 1.91" BT Calling Smartwatch', 'Fit Posh Smartwatch', 'Watch Pro', 'Cosmos Quest Smartwatch', 'ColorFit Caliber Smartwatch', 'Hurricane Smartwatch', 'ColorFit Icon 2 Smartwatch', 'Hurricane Smartwatch', 'Crusader Amoled 1.43BT Calling', 'TechLife Watch S100', 'Vigor HD Display Smartwatch', 'ColorFit Pro 5 Smartwatch', 'Cosmos Ultra 1.91" BT Calling Smartwatch', 'Evolve 3 Smartwatch', 'Avalanche Luxury Smart Watch', '1.91" HD Display Smartwatch', 'TechLife Watch S100', 'Eclipse Luxe 1.43" Amoled', 'FitGen Smart Watches', 'ColorFit Pro 5 Max Smartwatch', 'Grenade BT Calling Smartwatch', 'BT Calling Luxury Smartwatch', 'Enigma Z40 Smartwatch', 'Visionary TWS Smartwatch', 'FS2 BT Calling Smartwatch']

In [12]:
price=driver.find_elements(By.XPATH,".//span[@class='product-discountedPrice']")
prices=[i.text for i in price]

In [13]:
print(prices)

['Rs. 1899', 'Rs. 2299', 'Rs. 3199', 'Rs. 1899', 'Rs. 1799', 'Rs. 1899', 'Rs. 3499', 'Rs. 2799', 'Rs. 1699', 'Rs. 2299', 'Rs. 2249', 'Rs. 1799', 'Rs. 2299', 'Rs. 1799', 'Rs. 1599', 'Rs. 1599', 'Rs. 1899', 'Rs. 3499', 'Rs. 1799', 'Rs. 1700', 'Rs. 1899', 'Rs. 1999', 'Rs. 1799', 'Rs. 1799', 'Rs. 3499', 'Rs. 1599', 'Rs. 1799', 'Rs. 3499', 'Rs. 2499', 'Rs. 999', 'Rs. 1899', 'Rs. 1799', 'Rs. 1850', 'Rs. 1899', 'Rs. 2499', 'Rs. 2495', 'Rs. 3999', 'Rs. 1599', 'Rs. 2449', 'Rs. 2199', 'Rs. 2995', 'Rs. 2499', 'Rs. 1999', 'Rs. 3497', 'Rs. 4999', 'Rs. 1699', 'Rs. 1999', 'Rs. 4799', 'Rs. 2499', 'Rs. 1999']

In [28]:
y=driver.find_elements(By.XPATH,".//span[@class='product-discountPercentage']")
discount=[i.text for i in y]

In [14]:
brand=driver.find_elements(By.XPATH,".//h3[@class='product-brand']")
brands=[i.text for i in brand]

In [16]:
print(brands)

['Fire-Boltt', 'pebble', 'Fire-Boltt', 'boAt', 'NOISE', 'Fire-Boltt', 'CMF by Nothing', 'Cultsport', 'pebble', 'pebble', 'NOISE', 'Fire-Boltt', 'pebble', 'Fire-Boltt', 'pebble', 'Fire-Boltt', 'boAt', 'NOISE', 'NOISE', 'Fire-Boltt', 'boAt', 'Fire-Boltt', 'NOISE', 'Fire-Boltt', 'CMF by Nothing', 'pebble', 'NOISE', 'CMF by Nothing', 'pebble', 'NOISE', 'Fire-Boltt', 'NOISE', 'Fire-Boltt', 'Fire-Boltt', 'Realme', 'Fastrack', 'NOISE', 'pebble', 'NOISE', 'Fire-Boltt', 'Fastrack', 'Realme', 'Fire-Boltt', 'Timex', 'NOISE', 'Fire-Boltt', 'pebble', 'boAt', 'Fire-Boltt', 'Fastrack']

In [29]:
df=pd.DataFrame(columns=["Brand","Desc","Price","Discount"])
df

Empty DataFrame
Columns: [Brand, Desc, Price, Discount]
Index: []

In [30]:
df['Brand']=brands
df['Desc']=products
df['Price']=prices
df['Discount']=discount

In [31]:
df

,Brand,Desc,Price,Discount
0,Fire-Boltt,Cobra AMOLED Smart Watch,Rs. 1899,(Rs. 18100 OFF)
1,pebble,"Women 1.27"" Smart Watch",Rs. 2299,(Rs. 4700 OFF)
2,Fire-Boltt,Rock AMOLED Display Smartwatch,Rs. 3199,(Rs. 15800 OFF)
3,boAt,Unisex Wave Genesis Smartwatch,Rs. 1899,(Rs. 4600 OFF)
4,NOISE,Fit Posh Smartwatch,Rs. 1799,(Rs. 5200 OFF)
5,Fire-Boltt,Supernova Bluetooth SmartWatch,Rs. 1899,(Rs. 17100 OFF)
6,CMF by Nothing,Watch Pro,Rs. 3499,(Rs. 2500 OFF)
7,Cultsport,"Ace XR 1.43"" Smart Watches",Rs. 2799,(72% OFF)
8,pebble,"Hive 1.39"" Display Smart Watch",Rs. 1699,(Rs. 4800 OFF)
9,pebble,"Women 1.27"" Smart Watch",Rs. 2299,(Rs. 4700 OFF)
10,NOISE,Mettle EliteEdition Smartwatch,Rs. 2249,(Rs. 5750 OFF)
11,Fire-Boltt,Hulk 1.78 inch Smartwatch,Rs. 1799,(Rs. 16200 OFF)
12,pebble,"Celia 1.32"" Display SmartWatch",Rs. 2299,(Rs. 5200 OFF)
13,Fire-Boltt,"Eclipse Luxe 1.43"" Amoled",Rs. 1799,(Rs. 18200 OFF)
14,pebble,"Cosmos Ultra 1.91"" BT Calling Smartwatch",Rs. 1599,(Rs. 5900 OFF)
15,Fire-Boltt,Starlight Bluetooth Smartwatch,Rs. 1599,(Rs. 13400 OFF)
16,boAt,Ultima Connect Max HD Display,Rs. 1899,(Rs. 7100 OFF)
17,NOISE,ColorFit Vision 3 Smartwatch,Rs. 3499,(Rs. 4500 OFF)
18,NOISE,Fit Posh Smartwatch,Rs. 1799,(Rs. 5200 OFF)
19,Fire-Boltt,Hurricane Smartwatch,Rs. 1700,(Rs. 7299 OFF)
20,boAt,Ultima BT Calling Smartwatch,Rs. 1899,(Rs. 7100 OFF)
21,Fire-Boltt,Aura BT Calling Smartwatch,Rs. 1999,(Rs. 10000 OFF)
22,NOISE,ColorFit Icon 2 Smartwatch,Rs. 1799,(Rs. 5200 OFF)
23,Fire-Boltt,Hulk 1.78 inch Smartwatch,Rs. 1799,(Rs. 16200 OFF)
24,CMF by Nothing,Watch Pro,Rs. 3499,(Rs. 2500 OFF)
25,pebble,"Cosmos Ultra 1.91"" BT Calling Smartwatch",Rs. 1599,(Rs. 5900 OFF)
26,NOISE,Fit Posh Smartwatch,Rs. 1799,(Rs. 5200 OFF)
27,CMF by Nothing,Watch Pro,Rs. 3499,(Rs. 2500 OFF)
28,pebble,Cosmos Quest Smartwatch,Rs. 2499,(Rs. 7500 OFF)
29,NOISE,ColorFit Caliber Smartwatch,Rs. 999,(Rs. 3000 OFF)
30,Fire-Boltt,Hurricane Smartwatch,Rs. 1899,(Rs. 7100 OFF)
31,NOISE,ColorFit Icon 2 Smartwatch,Rs. 1799,(Rs. 5200 OFF)
32,Fire-Boltt,Hurricane Smartwatch,Rs. 1850,(Rs. 7149 OFF)
33,Fire-Boltt,Crusader Amoled 1.43BT Calling,Rs. 1899,(Rs. 17100 OFF)
34,Realme,TechLife Watch S100,Rs. 2499,(Rs. 1500 OFF)
35,Fastrack,Vigor HD Display Smartwatch,Rs. 2495,(Rs. 2500 OFF)
36,NOISE,ColorFit Pro 5 Smartwatch,Rs. 3999,(Rs. 5000 OFF)
37,pebble,"Cosmos Ultra 1.91"" BT Calling Smartwatch",Rs. 1599,(Rs. 5900 OFF)
38,NOISE,Evolve 3 Smartwatch,Rs. 2449,(Rs. 4550 OFF)
39,Fire-Boltt,Avalanche Luxury Smart Watch,Rs. 2199,(Rs. 18801 OFF)
40,Fastrack,"1.91"" HD Display Smartwatch",Rs. 2995,(Rs. 3000 OFF)
41,Realme,TechLife Watch S100,Rs. 2499,(Rs. 1500 OFF)
42,Fire-Boltt,"Eclipse Luxe 1.43"" Amoled",Rs. 1999,(Rs. 18000 OFF)
43,Timex,FitGen Smart Watches,Rs. 3497,(50% OFF)
44,NOISE,ColorFit Pro 5 Max Smartwatch,Rs. 4999,(Rs. 5000 OFF)
45,Fire-Boltt,Grenade BT Calling Smartwatch,Rs. 1699,(Rs. 14300 OFF)
46,pebble,BT Calling Luxury Smartwatch,Rs. 1999,(Rs. 8000 OFF)
47,boAt,Enigma Z40 Smartwatch,Rs. 4799,(Rs. 5700 OFF)
48,Fire-Boltt,Visionary TWS Smartwatch,Rs. 2499,(Rs. 16000 OFF)
49,Fastrack,FS2 BT Calling Smartwatch,Rs. 1999,(Rs. 2996 OFF)

In [33]:
df.to_csv("mytra.csv")